### ISSUE TITLE
Latest Proof

### ISSUE THREAD

**Issue by Afrotype** [Afrotype/festacrevival#11]
[Festac Proof, Letter.pdf](https://github.com/Afrotype/festacrevival/files/13500959/Festac.Proof.Letter.pdf)
(Wednesday, Nov 29)

**What's improved**
1. General spacing, counter-space consistency and stem width consistency.
2. More consistent colour across numbers.

**WIP**
1. Colour consistency across numbers.
2. Applying the angled terminals to Tft2?
4. Trying out Travis' recommendations.

**What we need feedback on**
1. New 2
2. Any other thing you see that we don't.

**Comment by traviskochel** [comment]
> We need feedback on the angled terminals on EFZ.

I like the angled terminals. I'm curious how it would feel on the `Tft2`, and anything else that has a horizontal stroke. It might be too much though?



> We need feedback on the upper and lowercase z.

I like how these are looking. Maybe the uppercase is a tad wide?



Also a few quick thoughts about punctuation:

- Maybe the question could be a simplified form similar to the 2
![IMG_5549](https://github.com/Afrotype/festacrevival/assets/980360/84d79e0c-0823-4c22-a0ad-9fdb588eedaf)

- Perhaps construction like this for brace `{}`? Also just making the middle pointier would help
![IMG_5550](https://github.com/Afrotype/festacrevival/assets/980360/ab3d7ea2-2c18-4087-a40d-fec51749750a)

- Perhaps the Breve could be curved rather than two separate strokes. I know this is breaking from your system, but it might help with distinguishing it from a Caron. I guess make sure it curves enough to distinguish from the Macron though.
![IMG_5551](https://github.com/Afrotype/festacrevival/assets/980360/857dfe11-cec8-4b6f-81b4-713235c82182)

**Comment by Afrotype** [comment]
Thank you @traviskochel . We'll work on these in the next round!

**Comment by traviskochel** [comment]
I just took a look at today's updated proof, and it's really starting to come along! 

The new two works for me. I am sad the other one didn't work out, but it's probably the right call.

Two other notes. 
- The `A` feels a little heavy, when looking at it in the paragraph samples.
- I’m wondering if the `VWvw` forms could use some exploration. They feel like they're leaning forward, compared to the rest of the design which is pretty vertical. Maybe the strokes could just stay straight? Or perhaps you could use the `A` as the basis?

**Comment by Afrotype** [comment]
[Festac Proof, Letter 2024-01-30 at 14.35.53.pdf](https://github.com/Afrotype/tac/files/14099175/Festac.Proof.Letter.2024-01-30.at.14.35.53.pdf)

**What's been updated**
Diacritics: Fully designed
Punctuation: Fully designed
Symbols: Fully designed
Cutouts: Fully designed and merged
Burnishing: We have burnished all the sharp corners.

**WIP**
Language Support: We are currently proofing and refining.
Kerning: We have started kerning
Fractions: We are refining fractions.

**What we need feedback on**
Drawing: Any letters that seem problematic or could look better? Please let us know.
Language support from the Vietnamese specialists
Fractions: Proportions of numbers, etc

**Comment by traviskochel** [comment]
This is looking great! A few suggestions:

- The counters on the `8` look a bit tight. If you can get them at least the size of your `e` counter, it might feel a little more comfortable. 
- In the fractions, is it possible to open up the counters in `2,4,6,8,9`? Maybe a combination of slightly lightening the strokes and widening the glyphs?
- I’m not familiar with how this glyph should look, but perhaps an overlap issue?
![Screen Shot 2024-01-30 at 10 11 32 AM](https://github.com/Afrotype/tac/assets/980360/ad1322cf-bc29-4fa7-9887-dd42ab42474a)

- I know you’re only starting kerning, but the `ra` popped out to me as too loose.
![Screen Shot 2024-01-30 at 10 16 46 AM](https://github.com/Afrotype/tac/assets/980360/c2fdb9fa-7c3f-4911-ad57-6055e05f5d20)
