### ISSUE TITLE
Burnishing Sharp/Acute Angles

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/festacrevival#12]
Per our call the other week, turning the sharp one-point angles into two-point ones for greater balance and harmony. 
<img width="485" alt="Screenshot 2023-12-10 at 8 43 09 PM" src="https://github.com/Afrotype/festacrevival/assets/8194236/c2de6973-ccb0-4c4d-a0fe-5c48378ca67b">

**Comment by bghryct** [comment]
hey @samarskaya I think that this is going to happen as a finishing step. To elaborate on that a bit; because of time constraints the idea is that someone on the team will go through as a production step and burnish everything. If you feel like this step should be incorporated imminently please let us know. 

Put another way. Are there any negatives that might arise from doing the burnishing at the end of the process as opposed to doing them during?

**Comment by samarskaya** [comment]
Absolutely — just here as a reminder so we don’t have to keep it in our minds in the meantime. 🙂

**Comment by bghryct** [comment]
this is in progress, and will be in the completed file.
